; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30151.0 

	TITLE	c:\code\mc\release\tiny-c.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	_here
PUBLIC	_num_nodes
PUBLIC	_ch
PUBLIC	_words
PUBLIC	_input_fp
EXTRN	__imp__getchar:PROC
EXTRN	__imp____stdio_common_vfprintf:PROC
EXTRN	__imp__fgetc:PROC
EXTRN	__imp__fclose:PROC
EXTRN	__imp____acrt_iob_func:PROC
EXTRN	__imp__fopen:PROC
EXTRN	___report_rangecheckfailure:PROC
EXTRN	__imp__exit:PROC
EXTRN	@__security_check_cookie@4:PROC
COMM	_vm:BYTE:03e8H
COMM	_id_hash:DWORD
COMM	_sp:DWORD
COMM	_nodes:BYTE:04e20H
COMM	_sym:DWORD
_num_nodes DD	01H DUP (?)
COMM	_id_name:BYTE:040H
_input_fp DD	01H DUP (?)
COMM	_vars:DWORD:0800H
COMM	_funcs:DWORD:0800H
COMM	_rsp:DWORD
COMM	_int_val:DWORD
_DATA	ENDS
_words	DD	FLAT:$SG4294967291
	DD	FLAT:$SG4294967290
	DD	FLAT:$SG4294967289
	DD	FLAT:$SG4294967288
	DD	FLAT:$SG4294967287
	DD	FLAT:$SG4294967286
	DD	00H
$SG4294967291 DB 'do', 00H
	ORG $+1
$SG4294967290 DB 'else', 00H
	ORG $+3
$SG4294967289 DB 'if', 00H
	ORG $+1
$SG4294967288 DB 'while', 00H
	ORG $+2
$SG4294967287 DB 'void', 00H
	ORG $+3
$SG4294967286 DB 'int', 00H
_here	DD	FLAT:_vm
_ch	DD	020H
_DATA	ENDS
PUBLIC	_main
PUBLIC	_compile
PUBLIC	_dis
PUBLIC	_run
PUBLIC	_f2
PUBLIC	_f4
PUBLIC	_c
PUBLIC	_fix
PUBLIC	_hole
PUBLIC	_g2
PUBLIC	_g4
PUBLIC	_g
PUBLIC	_program
PUBLIC	_statement
PUBLIC	_paren_expr
PUBLIC	_expr
PUBLIC	_test
PUBLIC	_sum
PUBLIC	_mathop
PUBLIC	_term
PUBLIC	_expect_sym
PUBLIC	_gen
PUBLIC	_new_node
PUBLIC	_next_sym
PUBLIC	_lcomment
PUBLIC	_isAlphaNum
PUBLIC	_isNum
PUBLIC	_isAlpha
PUBLIC	_hash
PUBLIC	_next_ch
PUBLIC	_syntax_error
PUBLIC	_error
PUBLIC	_message
PUBLIC	_printf
PUBLIC	_fprintf
PUBLIC	__vfprintf_l
PUBLIC	___local_stdio_printf_options
EXTRN	__chkstk:PROC
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
$SG4294967282 DB 01H DUP (?)
_BSS	ENDS
$SG4294967250 DB '-stack not empty-', 00H
	ORG $+2
$SG4294967251 DB '[%d] = %d', 0aH, 00H
	ORG $+1
$SG4294967253 DB 'code: %d bytes)', 0aH, 00H
	ORG $+3
$SG4294967254 DB '(nodes: %d, ', 00H
	ORG $+3
$SG4294967255 DB 'rt', 00H
	ORG $+1
$SG4294967256 DB 'main', 00H
	ORG $+3
$SG4294967257 DB 0aH, 00H
	ORG $+2
$SG4294967258 DB 'halt', 00H
	ORG $+3
$SG4294967259 DB 'ret', 00H
$SG4294967260 DB 'call %d [hash:%d]', 00H
	ORG $+2
$SG4294967261 DB 'jnz %d', 00H
	ORG $+1
$SG4294967262 DB 'jz %d', 00H
	ORG $+2
$SG4294967263 DB 'jmp %d', 00H
	ORG $+1
$SG4294967264 DB 'gt', 00H
	ORG $+1
$SG4294967265 DB 'lt', 00H
	ORG $+1
$SG4294967266 DB 'div', 00H
$SG4294967267 DB 'mul', 00H
$SG4294967268 DB 'sub', 00H
$SG4294967269 DB 'add', 00H
$SG4294967270 DB 'drop', 00H
	ORG $+3
$SG4294967271 DB 'lit4 %d', 00H
$SG4294967272 DB 'lit2 %d', 00H
$SG4294967273 DB 'lit1 %d', 00H
$SG4294967274 DB 'store [%d]', 00H
	ORG $+1
$SG4294967275 DB 'fetch [%d]', 00H
	ORG $+1
$SG4294967276 DB 0aH, '%04d: %02d ; ', 00H
	ORG $+1
$SG4294967277 DB '; there is no main() function', 00H
	ORG $+2
$SG4294967278 DB '; main() is at %d', 00H
	ORG $+2
$SG4294967279 DB 'list.txt', 00H
	ORG $+3
$SG4294967280 DB 'wt', 00H
	ORG $+1
$SG4294967281 DB '-expected symbol[%d],not[%d]-', 00H
	ORG $+2
$SG4294967283 DB '-ch-', 00H
	ORG $+3
$SG4294967284 DB '-syntax error-', 00H
	ORG $+1
$SG4294967285 DB '%s', 0aH, 00H
_DATA	ENDS
END
